Mixer ss
Programming-TRIGON/RobotCode2020 pull request #12
Opened 2020-01-19 17:16 UTC by OhadLevine

Get current is used for a specific command hilel asked for.
please cr

2020-01-19 17:30 UTC, EliyaFishman requested changes
good job

2020-01-19 17:30 UTC, EliyaFishman commented on src/main/java/frc/robot/constants/RobotMap.java
remove empty line

2020-01-19 17:30 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Mixer.java
> +    motor.set(ControlMode.PercentOutput, power);
replace `motor.set(ControlMode.PercentOutput, power);` with `motor.set(power);`

2020-01-19 17:30 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Mixer.java
> +  public double getStall(){
add docs

2020-01-19 17:31 UTC, EliyaFishman requested changes

2020-01-19 17:31 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Mixer.java
> +    motor.set(ControlMode.PercentOutput, power);
add `@Override`

2020-01-19 17:46 UTC, OhadLevine commented
done

2020-01-19 18:15 UTC, EliyaFishman requested changes
Move mixer to subsystems/mixer

2020-01-20 14:52 UTC, EliyaFishman requested changes

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +      notOnTarget = Timer.getFPGATimestamp() - startTime;
why target? there isn't any vision in here. Also remove start time

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +    startTime = Timer.getFPGATimestamp();
remove start time

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +    if (Timer.getFPGATimestamp() - startTime - notOnTarget > waitTime){
remove `- startTime`

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +    Robot.mixer.move(0);
replace with `mixer.stopMove();`

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +      Robot.mixer.move(speed);
replace two lines with `mixer.move(-power.getAsDouble());`

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  public SpinMixer(double power, double maxStall) {
we would probably want a constant maxStall. Move maxStall to RobotConstants

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +      notOnTarget = Timer.getFPGATimestamp() - startTime;
We want to just change direction when the stall is big enough. It should still speed even if that bellow

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +import frc.robot.Robot;
replace `import frc.robot.Robot;` with `import static frc.robot.Robot.mixer;`

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +
remove empty line

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  private double startTime;
remove start time as it's not needed

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +    if (Robot.mixer.getStall() < maxStall){
replace `Robot.mixer.getStall()` with `mixer.getStall()`

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  public boolean isFinished() {
delete method as you don't change anything from CommandBase

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/utils/DashboardDataContainer.java
> +        SmartDashboard.putNumber("Mixer Power", 0.0);
replace "Mixer Power" with "Mixer/Mixer Power".
This makes a subtable of mixer so shuffleboard is cleaner

2020-01-20 14:52 UTC, EliyaFishman commented on src/main/java/frc/robot/utils/DashboardDataContainer.java
> +        SmartDashboard.putData("Spin Mixer", new SpinMixer(SmartDashboard.getNumber("Mixer Power", 0.0), 0));
replace "Spin Mixer" "Mixer/Spin Mixer"

2020-01-20 16:58 UTC, EliyaFishman approved these changes

2020-01-20 21:56 UTC, HilelAmiel requested changes
few changes

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +        public double MIXER_MAX_STALL;
add inverted

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotMap.java
> +    public int MIXER_TALON;
MIXER_TALON_SRX

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/Mixer.java
> +    talon = new WPI_TalonSRX(robotConstants.can.MIXER_TALON);
add coast, inverted

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  private double waitTime;
set waitTime..?

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +      mixer.move(power.getAsDouble());
mixer.move(power.getAsDouble());
move to:

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +    }
} else {
      mixer.move(power.getAsDouble()); //here
}

2020-01-20 21:56 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  public void execute() {
change method for flipping (wont work)

2020-01-21 13:33 UTC, HilelAmiel requested changes
change last things

2020-01-21 13:33 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +    public static class MixerConstants {
public static class MixerConstants {
move after drivetrain constans

2020-01-21 13:33 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/Mixer.java
> +  private final WPI_TalonSRX talon;
talon to talonSRX

2020-01-21 13:33 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/SpinMixer.java
> +  private double changeDirectionTime;
changeDirectionTime what is for? not used

2020-01-21 13:33 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/Mixer.java
> +    talon.setInverted(robotConstants.mixerConstants.kIsInverted);
we might want ramp limit...

2020-01-21 14:12 UTC, HilelAmiel approved these changes

2020-01-21 14:12 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +    public static class MixerConstants {
you did that?

2020-01-21 14:13 UTC, merged