added intake with moshe reiview
Programming-TRIGON/RobotCode2020 pull request #13
Opened 2020-01-19 17:40 UTC by OhadLevine

this class collects the power cells

2020-01-19 17:44 UTC, EliyaFishman requested changes

2020-01-19 17:44 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Intake.java
> + * This Class holds all the methods for the intake which collects POWER CELLs
change POWER CELLs to POWER CELLS

2020-01-19 17:44 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Intake.java
> +    motor = new CANSparkMax(robotConstants.can.INTAKE_SPARK_MAX, MotorType.kBrushless);
invert motor by a boolean robotConstant

2020-01-19 18:17 UTC, EliyaFishman submitted a review, later dismissed

2020-01-19 18:17 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/Intake.java
> +package frc.robot.subsystems;
move to `frc.robot.subsystems.intake`

2020-01-19 18:24 UTC, OhadLevine commented
done

2020-01-20 16:35 UTC, OhadLevine commented
![](https://github.trello.services/images/mini-trello-icon.png) [Intake Subsystem](https://trello.com/c/ehCfTWpB/75-intake-subsystem)

2020-01-20 16:50 UTC, HilelAmiel requested changes
few things

2020-01-20 16:50 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +    }
isIntakeReversed
to 
kReversed

2020-01-20 16:50 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/SetIntakeSpeed.java
> +    @Override
}
// too many blank spaces

    @Override

2020-01-20 16:50 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/SetIntakeSpeed.java
> +    }
add subsystem requirement to both constractors

2020-01-21 12:46 UTC, HilelAmiel requested changes
two things

2020-01-21 12:46 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> + * This Class holds all the methods for the intake which collects POWER CELLS
This class

2020-01-21 12:46 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/SetIntakeSpeed.java
> +
too many spaces

2020-01-21 12:46 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +  private CANSparkMax motor;
motor to sparkMax

2020-01-21 15:20 UTC, HilelAmiel requested changes
sparkMax.setIdleMode(IdleMode.kCoast);

2020-01-21 15:20 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +    sparkMax.setInverted(robotConstants.intakeConstants.kIntakeReversed);
sparkMax.setIdleMode(IdleMode.kCoast);

2020-01-21 15:26 UTC, OhadLevine commented
done, waiting renewed cr

2020-01-21 15:36 UTC, HilelAmiel approved these changes

2020-01-21 16:17 UTC, merged