Move Movable Subsystem
Programming-TRIGON/RobotCode2020 pull request #16
Opened 2020-01-20 19:11 UTC by OhadLevine

2020-01-20 19:12 UTC, OhadLevine commented
![](https://github.trello.services/images/mini-trello-icon.png) [Command: MoveMoveableSubsystem](https://trello.com/c/bYtQmNtk/114-command-movemoveablesubsystem)

2020-01-20 20:30 UTC, HilelAmiel requested changes
few things

2020-01-20 20:30 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/MoveMovableSubsystem.java
> +
private double power;
make supplier

2020-01-20 20:30 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/MoveMovableSubsystem.java
> +    this(subsystem, power, () -> false);
this constructor first then the second

2020-01-20 20:30 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/MoveMovableSubsystem.java
> +  /** This command can move any subsystem that implements MovableSubsytem. */
/** This command can move any subsystem that implements MovableSubsytem. */
this constructor uses BooleanSupplier for... etc.

2020-01-21 06:51 UTC, EliyaFishman requested changes

2020-01-21 06:51 UTC, EliyaFishman commented on src/main/java/frc/robot/commands/MoveMovableSubsystem.java
> +
remove empty line

2020-01-21 13:47 UTC, OhadLevine commented
fixed a second time

2020-01-21 14:22 UTC, EliyaFishman approved these changes

2020-01-21 15:51 UTC, HilelAmiel requested changes
last chance

2020-01-21 15:51 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/MoveMovableSubsystem.java
> +   * an isFinished
without an isFinished
really?? I am a programmer who didn't write the code. What should I understand from this??

2020-01-21 16:01 UTC, OhadLevine commented
done

2020-01-21 16:19 UTC, HilelAmiel approved these changes

2020-01-21 16:19 UTC, merged