Rotate drivetrain CMD
Programming-TRIGON/RobotCode2020 pull request #20
Opened 2020-01-21 20:27 UTC by OhadLevine

2020-01-21 21:05 UTC, HilelAmiel requested changes
few things

2020-01-21 21:05 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java
> +  public boolean isFinished() {
end after isFinished

2020-01-21 21:05 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java
> +  TrigonPIDController pidController;
private

2020-01-21 21:05 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java
> +  public RotateDrivetrain() {
add to the data container this command so it will be ready to config the PID

2020-01-21 21:12 UTC, EliyaFishman requested changes

2020-01-21 21:12 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java
> +    drivetrain.arcadeDrive(pidController.trigonCalculate(drivetrain.getAngle(), desiredAngle.getAsDouble()), 0);
you can replace `drivetrain.arcadeDrive` with `drivetrain.move`

2020-01-22 15:46 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Drivetrain Command: turn in place](https://trello.com/c/TubvyR1N/111-drivetrain-command-turn-in-place)

2020-01-22 21:03 UTC, HilelAmiel approved these changes

2020-01-22 21:05 UTC, EliyaFishman approved these changes

2020-01-22 21:06 UTC, merged