Override Subsystems and Command
Programming-TRIGON/RobotCode2020 pull request #37
Opened 2020-01-23 23:21 UTC by EliyaFishman

2020-01-24 14:14 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Override subsystems and commands](https://trello.com/c/rwIn9Gqe/133-override-subsystems-and-commands)

2020-01-26 00:04 UTC, HilelAmiel requested changes
little change

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/OverridableSubsystem.java
> +        if (!overridden)
and what if power=0 ? like in stopMove?

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/OverridableSubsystem.java
> +            overrideNotifier.stop();
overrideNotifier.stop();
you should stopMove() after notifier.stop();

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +public class Intake extends OverridableSubsystem implements MovableSubsystem {
public class Intake extends OverridableSubsystem implements MovableSubsystem {
no need implements MovableSubsystem... OverridableSubsystem does it!

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/loader/Loader.java
> +public class Loader extends OverridableSubsystem implements MovableSubsystem {
no need implements MovableSubsystem {

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/mixer/Mixer.java
> +public class Mixer extends OverridableSubsystem implements MovableSubsystem {
implements MovableSubsystem {

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/shooter/CheesySetShooterVelocity.java
> +        if (shooter.isOverridden())
just a question. why return true? we would want to shoot only when the overridden speed would be enough...

2020-01-26 00:04 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +public class Shooter extends OverridableSubsystem implements MovableSubsystem {
implements MovableSubsystem {

2020-01-26 07:09 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/OverridableSubsystem.java
> +        if (!overridden)
We still don't want that commands will suddenly stop the subsystem

2020-01-26 07:12 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/shooter/CheesySetShooterVelocity.java
> +        if (shooter.isOverridden())
Because if the sensor is disconnected,
how would we know that we are at the right velocity?

2020-01-26 10:41 UTC, HilelAmiel approved these changes
good

2020-01-26 10:49 UTC, merged