Sensors disconnect detection
Programming-TRIGON/RobotCode2020 pull request #43
Opened 2020-01-24 10:55 UTC by HilelAmiel

- check command 
- subsystem error code check

2020-01-24 13:08 UTC, EliyaFishman requested changes
change

2020-01-24 13:08 UTC, EliyaFishman commented on src/main/java/frc/robot/components/Pigeon.java
> +    }
we can just make reset() return ErrorCode. I don't see why would we need two separate pigeon reset methods

2020-01-24 13:08 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +            DriverStationLogger.logErrorToDS("Could not set right shooter encoder");
Use the new DriverStationLogger method instead

2020-01-24 13:08 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +            DriverStationLogger.logErrorToDS("Could not set left shooter encoder");
Use the new DriverStationLogger method instead

2020-01-24 13:08 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/loader/Loader.java
> +            DriverStationLogger.logErrorToDS("Could not set loader encoder");
Use the new DriverStationLogger method instead

2020-01-24 13:08 UTC, EliyaFishman commented on src/main/java/frc/robot/utils/DriverStationLogger.java
> +import com.ctre.phoenix.ErrorCode;
import static should be after import

2020-01-24 14:13 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [IsAlive sensor detecting](https://trello.com/c/o3t81oRu/124-isalive-sensor-detecting)

2020-01-25 20:16 UTC, EliyaFishman requested changes
Really good but You still didn't change that Pigeon should only have one reset method instead of two so, please change

2020-01-25 20:16 UTC, EliyaFishman commented on src/main/java/frc/robot/commands/SensorCheck.java
> +    for (; i < hasFoundError.length; i++) {
move int i to for

2020-01-26 09:56 UTC, HilelAmiel reviewed
lol

2020-01-26 09:56 UTC, HilelAmiel commented on src/main/java/frc/robot/components/Pigeon.java
> +    }
The return type is incompatible with Gyro.reset()

2020-01-26 09:56 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/SensorCheck.java
> +    for (; i < hasFoundError.length; i++) {
but i's scope would be only in the for block and I use i outside the for block and that is why he should be created locally on the method block

2020-01-26 09:57 UTC, EliyaFishman approved these changes

2020-01-26 09:57 UTC, merged