added the rumble function
Programming-TRIGON/RobotCode2020 pull request #48
Opened 2020-01-27 13:33 UTC by Mboesn

2020-01-27 14:00 UTC, HilelAmiel requested changes
come on

2020-01-27 14:00 UTC, HilelAmiel commented on src/main/java/frc/robot/utils/TrigonXboxController.java
> +    public void setRumble(boolean isRumble) {
public void setRumble(boolean isRumble) {
just do:
    `public void setRumble(double power) {
            setRumble(RumbleType.kLeftRumble, power);
            setRumble(RumbleType.kRightRumble, power);
     }`

2020-01-27 14:00 UTC, HilelAmiel commented on src/main/java/frc/robot/utils/TrigonXboxController.java
> +                setRumble(true);
here do: 
`setRumble(1); // Full rumble power`

2020-01-27 14:00 UTC, HilelAmiel commented on src/main/java/frc/robot/utils/TrigonXboxController.java
> +                setRumble(false);
here do: 
`setRumble(0);`

2020-01-27 14:00 UTC, HilelAmiel commented on src/main/java/frc/robot/utils/TrigonXboxController.java
> +        if (rumbleAmount > 0) {
if (rumbleAmount > 0) {
to 
        if (rumbleAmount >= 0) {

2020-01-27 14:18 UTC, HilelAmiel reviewed
important thing

2020-01-27 14:18 UTC, HilelAmiel commented on src/main/java/frc/robot/utils/TrigonXboxController.java
> +    private static final double kIntermittentRumbleTime = 0.5;
**Make it 0.15** we tested it and this value works great

2020-01-27 16:43 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [add rumble method to TrigonXboxController class](https://trello.com/c/iOp3cYSj/140-add-rumble-method-to-trigonxboxcontroller-class)

2020-01-29 13:08 UTC, HilelAmiel approved these changes

2020-01-29 13:08 UTC, merged