Commands and command groups fixes
Programming-TRIGON/RobotCode2020 pull request #49
Opened 2020-01-27 14:03 UTC by EliyaFishman

Fixes #46

2020-01-27 15:26 UTC, HilelAmiel requested changes
change

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/RunTwoCommands.java
> +     *
blank line

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/RunTwoCommands.java
> +        runningCommand.initialize();
why not use `.schedule();` and `.cancel();` ? I think it would save you initialize and execute lines

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/RunTwoCommands.java
> +        this.ifFalse = ifFalse;
what if ifTrue or ifFalse commands are **null**?

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/robots/RobotA.java
> +        loaderConstants.kDefaultBackwardsPower = 0.2;
**-** 0.2?

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +        public double kDefaultUnjamPower;
public double kDefaultUnjamPower;
what is Unjam?

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/commands/command_groups/AutoShoot.java
> +                new RunTwoCommands(SetLoaderVelocity.defaultSetLoaderVelocityCommand(),
add another tolerance for this condition

2020-01-27 15:26 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java
>       */
A suggestion, add DriveWithXbox as default command

2020-01-27 16:25 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Commands fixes](https://trello.com/c/oYbBJiE3/144-commands-fixes)

2020-01-27 16:26 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Commands fixes](https://trello.com/c/oYbBJiE3/144-commands-fixes)

2020-01-29 18:08 UTC, HilelAmiel approved these changes

2020-01-29 18:08 UTC, HilelAmiel commented on src/main/java/frc/robot/OI.java
> +        drivetrain.setDefaultCommand(new DriveWithXbox(() -> driverXbox.getX(Hand.kLeft), () -> driverXbox.getY(Hand.kLeft)));
no.







you should make y as the deltaTriggers value...

2020-01-29 18:09 UTC, merged