Support for Falcon Dashboard
Programming-TRIGON/RobotCode2020 pull request #54
Opened 2020-02-01 19:37 UTC by EliyaFishman

Follow path was changed to get the X and Y values of the path.
Use [the modified falcon dashboard]( https://github.com/EliyaFishman/FalconDashboard/releases) to check it.

2020-02-01 20:34 UTC, HilelAmiel requested changes
make the code as minimal as you can...

2020-02-01 20:34 UTC, HilelAmiel commented on src/main/java/frc/robot/motion_profiling/FollowPath.java
> +
remove

2020-02-01 20:34 UTC, HilelAmiel commented on src/main/java/frc/robot/motion_profiling/FollowPath.java
> + * <p>The command handles trajectory-following, PID calculations, and feedforwards internally.  This
internally.  This 
too many spaces

2020-02-01 20:34 UTC, HilelAmiel commented on src/main/java/frc/robot/motion_profiling/FollowPath.java
> +    private FollowPath(Trajectory trajectory,
remove... make the code as minimal as you can...

2020-02-03 13:47 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use Falcon Dashboard For motion profiling](https://trello.com/c/5XGl8OzU/136-use-falcon-dashboard-for-motion-profiling)

2020-02-04 00:07 UTC, HilelAmiel approved these changes

2020-02-04 00:08 UTC, merged