Fix FollowPath bugs
Programming-TRIGON/RobotCode2020 pull request #62
Opened 2020-02-04 15:25 UTC by EliyaFishman

Now it no longer resets all the time the path when tuning and allows for hotswaping trajectories

2020-02-04 18:49 UTC, EliyaFishman commented
Generated paths still need to be tested with on the robot with falcon dashboard so we can know that the max velocity, acceleration, and constraints are good

2020-02-04 20:35 UTC, EliyaFishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Auto Command groups](https://trello.com/c/3T7xL1aP/131-create-auto-command-groups)

2020-02-05 08:40 UTC, HilelAmiel requested changes
many

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
> +        autoChooser.setDefaultOption("Simple Auto", new SimpleAuto());
add another SendableChooser for start pose

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/RendezvousAuto.java
> +public class RendezvousAuto extends SequentialCommandGroup {
RendezvousAuto what is that name?

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/robots/RobotA.java
> +        autoConstants.kSimpleAutoTimeout = 0.2;
autoConstants.kSimpleAutoTimeout = 0.2;
rise to 0.85

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/robots/RobotA.java
> +        autoConstants.kSimpleAutoPower = 0.5;
autoConstants.kSimpleAutoPower = 0.5;
lower to 0.3

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/motion_profiling/FollowPath.java
> +                DriverStationLogger.logErrorToDS("Failed to deserialize trajectory");
can you add path name?

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/motion_profiling/FollowPath.java
> +        SmartDashboard.putNumber("Falcon/PathY", curState.poseMeters.getTranslation().getY());
SmartDashboard.putNumber("Falcon/PathX", curState.poseMeters.getTranslation().getX());
        SmartDashboard.putNumber("Falcon/PathY", curState.poseMeters.getTranslation().getY());
make one method: void updateXY()

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/SimpleAuto.java
> +        super.initialize();
```suggestion
        super.initialize();
        timer.reset();
        timer.start();
```

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/SimpleAuto.java
> +            drivetrain).withInterrupt(() -> timer.hasPeriodPassed(timeout.getAsDouble())),
why use .withInterrupt? you can use .withTimeout​(double seconds)

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/SimpleAuto.java
> +            new AutoShoot()
```suggestion
            new AutoShoot(true)
```
we are in auto

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/TrenchAuto.java
> +            new AutoShoot(true),
add wait command... of 0.1 seconds. The shooter detects that the ball has been shot but it takes a little bit of time for the actual ball to fly away from the robot. Use: `new WaitCommand​(double timeout)` 
**OR BETTER:** add to AutoShoot that if it is in auto mode (gets true in the constructor) the AutoShoot need to add `new WaitCommand​(double timeout)` at the end of it...

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/TrenchAuto.java
> +            new AutoShoot(true)
You have to rotate to the power port before shooting, and you cant shoot under the trench, so rotate, get close to the power port near the start of the trench run and then **shoot!**
**ALSO** the last AutoShoot(true) should be: AutoShoot() without shoot limit of 3 cells (you can make AutoShoot gets the number of cells to shoot).
good luck!

2020-02-05 08:40 UTC, HilelAmiel commented on src/main/java/frc/robot/autonomus/RendezvousAuto.java
> +            new AutoShoot(true)
**see the comments in TrenchAuto first!** 

you cant shoot right away.

2020-02-05 12:33 UTC, EliyaFishman commented on src/main/java/frc/robot/autonomus/SimpleAuto.java
> +            drivetrain).withInterrupt(() -> timer.hasPeriodPassed(timeout.getAsDouble())),
timeout gets a double. We can't play with the timeout supplier this way as withTimeout is called only one time

2020-02-05 22:19 UTC, HilelAmiel approved these changes

2020-02-05 22:21 UTC, merged