Trigon drive
Programming-TRIGON/RobotCode2020 pull request #9
Opened 2020-01-16 21:40 UTC by Mboesn

2020-01-17 12:22 UTC, EliyaFishman requested changes

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/constants/RobotConstants.java
> +        public boolean X_LOCK;
Remove all x lock occurrences. We use commands that require drivetrain instead of x locking

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/constants/robots/RobotA.java
> +        trigonDriveConstents.X_LOCK = false;
remove

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    private boolean xLock;
remove

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +        this.xLock = xLock;
remove

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    }
remove

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    }
remove

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public double yInputcalculation(double value) {
change the name to `yInputCalculation`

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +        boolean isLinear = Math.abs(value) <= 0.25;
move magic number to constant

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public double xyInputcalculation(double value) {
for what this function exist?

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public double yInputcalculation(double value) {
for what this function exist?

2020-01-17 12:22 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public double xyInputcalculation(double value) {
rename to `xyInputCalculation`

2020-01-18 19:16 UTC, HilelAmiel requested changes
more cr

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +}
}
 // remove this blank line
}

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +        this.threshold = threshold;
public void setThreshold(double threshold) {
and after it:
    public double getThreshold() {
and the same to the Sensetivity methods

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +public class TrigonDrive extends DifferentialDrive {
// TODO: add documentation
remove

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    private double sensitivity;
// remove blank line
    private double sensitivity;

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +        super(leftMotor, rightMotor);
double threshold) {
move up,  and yes I know that it is long

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    }
robotConstants.trigonDriveConstents.SENSITIVITY, robotConstants.trigonDriveConstents.THRESHOLD);
up

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +        this.sensitivity = sensitivity;
setSensitivity
would we need that?

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +                Math.sqrt(yInput * yInput + xInput * xInput) < threshold || Math.abs(yInput) < Math.abs(xInput));
Math.sqrt(yInput * yInput + xInput * xInput) < threshold || Math.abs(yInput) < Math.abs(xInput));
one tab less

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    //     boolean isLinear = Math.abs(value) <= 0.5;
xyInputCalculation
to 
xInputCalculation
AND 
uncomment

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    //     return isLinear ? 2 * value : Math.signum(value) * Math.sqrt(Math.abs(value));
0.25 to class final Y_LINEAR_THRESHOLD
2 to class final y_linear_coefficient (all caps)

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    //     boolean isLinear = Math.abs(value) <= 0.25;
// public double yInputCalculation(double value) {
uncomment

2020-01-18 19:16 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    // }
0.5 to X_LINEAR_THRESHOLD
0.5 to x_linear_coefficient (all caps)

2020-01-18 21:47 UTC, HilelAmiel requested changes
so close...

2020-01-18 21:47 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public TrigonDrive(SpeedController leftMotor, SpeedController rightMotor) {
too many blank lines

2020-01-18 21:47 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    private final double X_LINEAR_THRESHOLD = 0.5;
private static final double

2020-01-18 21:47 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +                Math.sqrt(yInputCalculation(yInput) * yInputCalculation(yInput)
add: double x = xInputCalculation(xInput);
double y = yInputCalculation(yInput);
and use them

2020-01-19 16:58 UTC, EliyaFishman requested changes
It's pretty good. But we still need to wait for drivetrain merge before this can be merged

2020-01-19 16:58 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public TrigonDrive(SpeedController leftMotor, SpeedController rightMotor) {
What happened to the second constructor?

2020-01-19 17:25 UTC, EliyaFishman approved these changes

2020-01-19 18:28 UTC, EliyaFishman reviewed
Good I will review drivetrain next

2020-01-19 18:37 UTC, EliyaFishman commented
@HilelAmiel want to give it a quick look?

2020-01-19 18:40 UTC, EliyaFishman requested changes

2020-01-19 18:40 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
> +  public double getTrigonDrivSensitivity() {
driv

2020-01-19 18:40 UTC, EliyaFishman commented on src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
> +  public void setTrigonDrivThreshold(double threshold) {
driv

2020-01-20 20:24 UTC, HilelAmiel requested changes
one thing

2020-01-20 20:24 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
public TrigonDriveConstents trigonDriveConstents = new TrigonDriveConstents();
move this after drivetrainConstants

2020-01-20 20:24 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/RobotConstants.java
> +        public double SENSITIVITY;
move this after DrivetrainConstants

2020-01-20 20:24 UTC, HilelAmiel commented on src/main/java/frc/robot/constants/robots/RobotA.java
> +        trigonDriveConstents.THRESHOLD = 0;
move after driveConstents
and set:
SENSITIVITY = 1
THRESHOLD = 0.5

2020-01-20 20:24 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +    public TrigonDrive(SpeedController leftMotor, SpeedController rightMotor) {
we don't need it because we have default SENSITIVITY and if we want to change then use setSensitivity

2020-01-20 20:24 UTC, HilelAmiel commented on src/main/java/frc/robot/subsystems/drivetrain/TrigonDrive.java
> +            Math.sqrt(y * y + x * x) < threshold || Math.abs(y) < Math.abs(x));
curvatureDrive(sensitivity * x, sensitivity * y,
change x and y positions

2020-01-20 21:11 UTC, HilelAmiel approved these changes
finnaly

2020-01-20 21:11 UTC, merged